Create skeleton pipeline for project copy HCA
DataBiosphere/hca-ingest pull request #162
Opened 2021-07-26 19:16 UTC by eparkmonster

## Why
We need to start building the project copying tool in HCA and we need to create the skeleton to map out the structure first
[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1852)

## This PR
Creates the skeleton pipeline that utilizes the 6 solid stubs that we want to later implement
Also creates a test to see if the solids are passed through the pipeline
## Checklist
- [ ] Documentation has been updated as needed.

2021-07-27 12:45 UTC, aherbst-broad requested changes
Overall looks like a good start, some superficial naming and formatting issues that need addressing.

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/pipelines/copy_project.py
> +    create_data_file_ingestion(create_ingest_file_id(create_data_file_copy(create_tabular_ingestion(create_subgraph_hydration(create_scratch_area())))))
⛏️ This shouldn't be on a single line, it's not very readable in the current state

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/create_scratch_area.py
> +def create_scratch_area(context: AbstractComputeExecutionContext):
⛏️ This will need a return type for mypy to pass, `-> str:` should be fine for now.

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/data_file_copy.py
> +    return "scratch_bucket_name"
⛏️ Newline

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/data_file_copy.py
> +def create_data_file_copy(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ Same comment about return type for mypy.

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/data_file_ingestion.py
> +    return "scratch_bucket_name"
⛏️ Newline

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/data_file_ingestion.py
> +def create_data_file_ingestion(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ Return type

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/ingest_file_id.py
> +def create_ingest_file_id(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ This would be better named `inject_file_ids`

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/ingest_file_id.py
> +    return "scratch_bucket_name"
⛏️ newline

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/subgraph_hydration.py
> +def create_subgraph_hydration(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ Return type

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/tabular_data_ingestion.py
> +def create_tabular_ingestion(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ This would be better named `ingest_tabular_data` + add a return type

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/tabular_data_ingestion.py
> +    return "scratch_bucket_name"
⛏️ newline

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/data_file_copy.py
> +def create_data_file_copy(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ This would be better named `copy_data_files`

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/data_file_ingestion.py
> +def create_data_file_ingestion(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ This would be better named `ingest_data_files`

2021-07-27 12:45 UTC, aherbst-broad commented on orchestration/dagster_orchestration/hca_orchestration/solids/copy_project/subgraph_hydration.py
> +def create_subgraph_hydration(context: AbstractComputeExecutionContext, scratch_bucket_name: str):
⛏️ This would be better named `hydrate_subgraphs`

2021-07-28 13:00 UTC, aherbst-broad approved these changes

2021-07-28 13:16 UTC, quazi-broad approved these changes
skeleton looks good to me. not sure why that type check is returning an error since you do have those return types

2021-07-28 13:42 UTC, aherbst-broad commented
@quazi-broad I think mypy is getting confused because there is no `__init__.py` in the `solids/copy_project` module; @eparkmonster  just put an empty `__init__.py` file at that path and it should pass static type checks.

2021-07-28 14:11 UTC, merged