[DSPDC-1622] Fix invalid import
DataBiosphere/hca-ingest pull request #71
Opened 2021-03-09 22:29 UTC by aherbst-broad

## Why

[Relevant ticket](https://broadinstitute.atlassian.net/browse/DSPDC-1622)
The validator script does not run due to an invalid import.

## This PR
* Fixes the import

2021-03-10 14:07 UTC, raaidbroad approved these changes

2021-03-10 18:24 UTC, ThePletch requested changes
should be good to go once we switch the import location

2021-03-10 18:24 UTC, ThePletch commented on orchestration/dagster_orchestration/hca_utils/main.py
> +from hca_orchestration.sensors import default_google_access_token
:-1: this is an import from a file that imports it, let's import directly from the file where this method's defined instead:
```suggestion
from hca_orchestration.resources.base import default_google_access_token
```

2021-03-10 20:03 UTC, ThePletch approved these changes
🚂

2021-03-11 14:13 UTC, closed without merging

2021-03-11 14:14 UTC, aherbst-broad commented
This is no longer an issue in @raaidbroad 's in flight PR #72